coreConfig:
  externalEventConfig:
    sparkMasterWithPort: local[2]
    topicName: user.payments.external
    kafkaBrokerConnection: localhost:9092
    zkHosts: localhost
    zkPort: 2182
    kafkaConfig:
      heartBeatIntervalMS: 600
  internalEventProcessorConfig:
    sparkMasterWithPort: local[2]
    topicNames:
     - user.payments
    kafkaBrokerConnection: localhost:9092
    zkHosts: localhost
    zkPort: 2182
    kafkaConfig:
      heartBeatIntervalMS: 600
