server:
  gzip:
    bufferSize: 80KiB
    enabled: true
    minimumEntitySize: 256 bytes
  applicationConnectors:
    - type: http
      port: 9999
  adminConnectors:
    - type: http
      port: 9990
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/usl/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/usl/access.%d.log.gz
        archivedFileCount: 7
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout