server:
  gzip:
    bufferSize: 80KiB
    enabled: true
    minimumEntitySize: 256 bytes
  applicationConnectors:
    - type: http
      port: 9999
  adminConnectors:
    - type: http
      port: 9990
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/usl/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/usl/access.%d.log.gz
        archivedFileCount: 7
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout
swagger:
  resourcePackage: com.flipkart.gap.usl.resources
  title: Sample API
  version: v1
  description: Sample service API
  contact: gap-devs@flipkart.com
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
eventIngestionConfig:
  kafkaTopicName: local-usl
  kafkaIngestionConfig:
    brokerConnectionString: localhost:9092
    zkConnectionString: localhost:2181
coreConfig:
  applicationResilienceConfig:
    dimensionReadConfig:
      bulkheadConfig:
        maxConcurrentCalls: 100
        maxWaitDuration: 500
      circuitBreakerConfig:
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 100
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 100
        slowCallDurationThreshold: 300
        slowCallRateThreshold: 100
        failureRateThreshold: 50
      rateLimiterConfig:
        limitRefreshPeriod: 1000
        limitForPeriod: 12000
        timeoutDuration: 500
      timeLimiterConfig:
        timeoutDuration: 500
    eventIngestionConfig:
      bulkheadConfig:
        maxConcurrentCalls: 100
        maxWaitDuration: 500
      circuitBreakerConfig:
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 100
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 100
        slowCallDurationThreshold: 300
        slowCallRateThreshold: 100
        failureRateThreshold: 50
      rateLimiterConfig:
        limitRefreshPeriod: 1000
        limitForPeriod: 1000
        timeoutDuration: 200
      timeLimiterConfig:
        timeoutDuration: 500
    dimensionBulkReadConfig:
      bulkheadConfig:
        maxConcurrentCalls: 100
        maxWaitDuration: 500
      circuitBreakerConfig:
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 100
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 100
        slowCallDurationThreshold: 500
        slowCallRateThreshold: 100
        failureRateThreshold: 50
      rateLimiterConfig:
        limitRefreshPeriod: 1000
        limitForPeriod: 10000
        timeoutDuration: 500
      timeLimiterConfig:
        timeoutDuration: 60000
    dimensionBulkSaveConfig:
      bulkheadConfig:
        maxConcurrentCalls: 100
        maxWaitDuration: 500
      circuitBreakerConfig:
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 100
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 100
        slowCallDurationThreshold: 500
        slowCallRateThreshold: 100
        failureRateThreshold: 50
      rateLimiterConfig:
        limitRefreshPeriod: 1000
        limitForPeriod: 1000
        timeoutDuration: 500
      timeLimiterConfig:
        timeoutDuration: 60000
    dimensionDeleteConfig:
      bulkheadConfig:
        maxConcurrentCalls: 100
        maxWaitDuration: 500
      circuitBreakerConfig:
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 100
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 100
        slowCallDurationThreshold: 500
        slowCallRateThreshold: 100
        failureRateThreshold: 50
      rateLimiterConfig:
        limitRefreshPeriod: 1000
        limitForPeriod: 10
        timeoutDuration: 500
      timeLimiterConfig:
        timeoutDuration: 1000
  eventProcessorConfig:
    sparkMasterWithPort: local[2]
    topicName: local-usl
    kafkaBrokerConnection: localhost:9092
    zkHosts: localhost
    zkPort: 2181
  dimensionPackage: com.flipkart.usl.processor.sample
  mongoConfig:
    connectionString: localhost:27017
    dbName: local-usl
  hbaseConfig:
    tableName: local-usl
    zookeeperQuorum: localhost:2181
    parentNode: /hbase
  cacheConfig:
    ttlInMinutes: 30
healthCheckKey: blah
