cacheConfig:
  ttlInMinutes: 24
zkConfig:
  zookeperConnectionString: localhost:2181/usl/dev/offset
dimensionPackage: com.flipkart.gap.usl.app.dimension
eventProcessorConfig:
  sparkMasterWithPort: localhost:7077
  topicName: usl-dev-test
  kafkaBrokerConnection: localhost:9092
  environment: dev