server:
  applicationConnectors:
    - type: http
      port: 25001
  adminConnectors:
    - type: http
      port: 25002

  requestLog:
        appenders:
          - type: console
            timeZone: IST

logging:
  level: INFO
  loggers:
    flipkart.gap: DEBUG
  appenders:
    - type: console
      timeZone: IST
      logFormat: "%-5level[%date][%thread][%logger{0}] %message%n"

swagger:

  resourcePackage: com.flipkart.gap.usl.resources
  title: Sample API
  version: v1
  description: Sample service API
  contact: jplock@smoketurner.com
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
